name: NASA Project CI
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
    env: 
      MONGO_URL: mongodb://localhost/nasa
      CI: true
    strategy: 
      matrix: 
        node-version: [ 14.x, 16.x, 20.x ]
        mongodb-version: ['4.2', '4.4']

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Start MongoDB version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run build
      - run: npm test
